### ISSUE TITLE
npm install parse-function fails

### ISSUE THREAD

**Issue by estebanpanelli** [tunnckoCore/opensource#157]
When trying to install this package npm fails with following error

```
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/parse-function reason: Unexpected end of JSON input
```
### Log file contents

```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'parse-function@latest' ]
1 info using npm@7.7.5
2 info using node@v12.18.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/estebanpanelli/src/node/automate-wa/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/estebanpanelli/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 9ms
18 timing npm:load:configload Completed in 9ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 2ms
21 timing npm:load:cleanupLog Completed in 2ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 0ms
24 timing npm:load Completed in 16ms
25 timing config:load:flatten Completed in 3ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 45ms
28 timing arborist:ctor Completed in 1ms
29 http fetch GET 304 https://registry.npmjs.org/parse-function 594ms (from cache)
30 timing idealTree Completed in 643ms
31 timing command:install Completed in 652ms
32 verbose type invalid-json
33 verbose stack FetchError: invalid json response body at https://registry.npmjs.org/parse-function reason: Unexpected end of JSON input
33 verbose stack     at /usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:77:31
33 verbose stack     at async Arborist.[retrieveSpecName] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:465:18)
33 verbose stack     at async Promise.all (index 0)
33 verbose stack     at async Arborist.[applyUserRequests] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:419:7)
33 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
33 verbose stack     at async Promise.all (index 1)
33 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
33 verbose stack     at async Install.install (/usr/lib/node_modules/npm/lib/install.js:137:5)
34 verbose cwd /home/estebanpanelli/src/node/automate-wa
35 verbose Linux 5.8.0-48-generic
36 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "parse-function@latest"
37 verbose node v12.18.0
38 verbose npm  v7.7.5
39 error code FETCH_ERROR
40 error errno FETCH_ERROR
41 error invalid json response body at https://registry.npmjs.org/parse-function reason: Unexpected end of JSON input
42 verbose exit 1
```

Already tried to clean npm cache.

#### Context

- _node version_: 12.18.0
- _module version_: latest
- _environment_: Ubuntu Desktop

**Comment by tunnckoCore** [comment]
That isn't a problem from the package.
