### ISSUE TITLE
super weird bug in docs runner

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/opensource#63]
For some reason it throws this error, almost always.

```
(node:799081) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'config' of undefined
    at /home/charlike/github/tunnckoCore/opensource/node_modules/@jest/core/build/TestScheduler.js:289:28
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/charlike/github/tunnckoCore/opensource/node_modules/@jest/core/build/TestSc
heduler.js:131:24)
    at _next (/home/charlike/github/tunnckoCore/opensource/node_modules/@jest/core/build/TestScheduler.js:15
1:9)
    at /home/charlike/github/tunnckoCore/opensource/node_modules/@jest/core/build/TestScheduler.js:156:7
    at new Promise (<anonymous>)
    at /home/charlike/github/tunnckoCore/opensource/node_modules/@jest/core/build/TestScheduler.js:148:12
    at onFailure (/home/charlike/github/tunnckoCore/opensource/node_modules/@jest/core/build/TestScheduler.js:302:26)
    at onError (/home/charlike/github/tunnckoCore/opensource/@tunnckocore/create-jest-runner/src/createJestRunner.js:137:9)
    at /home/charlike/github/tunnckoCore/opensource/@tunnckocore/create-jest-runner/src/createJestRunner.js:173:15
(node:799081) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
```

No matter which is the package. Super awful for debugging and always forgetting how we can see the actual error. Debugged it few times but... :D It's nothing related to `create-jest-runner`, there is no problems.

**Comment by tunnckoCore** [comment]
Turns out it was bug it `create-jest-runner`'s one of the onError calls was with wrong signature.
